"""
Django settings for projeto project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%1ar)i&68#4bb$j24axv0l+dwbe0rpdu#b)#b--3h^v-w*yyir'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['cmentor.pythonanywhere.com', '127.0.0.1', 'localhost', 'mentorias.local']

CSRF_TRUSTED_ORIGINS = ['http://mentorias.local', 'https://mentorias.local']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django_extensions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'app',
    'mentoria',
    'deisihub',
#    'impersonate',
]

import os

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Make sure this is set to DEBUG
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_app.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',  # Ensure this is also DEBUG
            'propagate': True,
        },
        'your_app_name': {  # Replace with your actual app name
            'handlers': ['file'],
            'level': 'DEBUG',  # Ensure this is set to DEBUG
            'propagate': False,
        },
    },
}



#IMPERSONATE = {
#    'URI_EXCLUSIONS': ['admin/', 'impersonate/stop/'],  # Exclude the admin and stop URLs from impersonation
#    'REQUIRE_SUPERUSER': True,  # Allow only superusers to impersonate
# }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]



SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

LOGIN_REDIRECT_URL = 'horarios:login'
LOGOUT_REDIRECT_URL = 'horarios:login'

ROOT_URLCONF = 'projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

RUN_ENV = os.getenv("RUN_ENV", "PA")   # "PA" (default) ou "CLUSTER"

DEBUG = os.getenv("DEBUG", "1" if RUN_ENV=="PA" else "0") == "1"


RUN_ENV = os.getenv("RUN_ENV", "LOCAL")   # LOCAL | PA | CLUSTER

if RUN_ENV == "PA":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'mentoriasDEISI$default',
            'USER': 'mentoriasDEISI',
            'PASSWORD': 'ProgramaMentoria',
            'HOST': 'mentoriasDEISI.mysql.pythonanywhere-services.com',
            'PORT': '3306',
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
        }
    }
    MEDIA_ROOT = '/home/mentoriasDEISI/projeto/media'
    STATIC_ROOT = '/home/mentoriasDEISI/projeto/static'

elif RUN_ENV == "CLUSTER":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DATABASE', 'mentorias'),
            'USER': os.getenv('MYSQL_USER', 'mentorias'),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', ''),
            'HOST': os.getenv('MYSQL_HOST', 'mysql'),
            'PORT': os.getenv('MYSQL_PORT', '3306'),
            'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
        }
    }
    MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

else:
    # === LOCAL (SQLite) ===
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    MEDIA_ROOT = BASE_DIR / 'media'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
STATIC_URL = '/static/'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'projeto.backends.EmailBackend',
]



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'Europe/Lisbon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info

#MEDIA_ROOT = '/home/mentoriasDEISI/projeto/media'
#MEDIA_URL = '/media/'
#STATIC_ROOT = '/home/mentoriasDEISI/projeto/static'
#STATIC_URL = '/static/'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mentoriadeisi@gmail.com'
EMAIL_HOST_PASSWORD = 'aqbs mqlr tiur jrad'  # usar uma google app password

LOGIN_URL = 'horarios:login'

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}
