# Generated by Django 4.0.6 on 2023-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='app/'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='app/'),
        ),
    ]
