# Generated by Django 4.0.6 on 2023-06-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ocorrencia_doc_ocorrencia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='app.tipoocorrencia'),
        ),
    ]
