# Generated by Django 4.0.6 on 2023-06-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ocorrencia_descricao_alter_ocorrencia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='app.colaborador'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='app.utente'),
        ),
    ]
