# Generated by Django 4.0.6 on 2023-07-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_colaborador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
    ]
