# Generated by Django 4.0.6 on 2023-07-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
