# Generated by Django 4.0.6 on 2023-07-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_colaborador_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='nome',
        ),
    ]
