# Generated by Django 4.0.6 on 2023-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_mentor_aluno_remove_mentor_disciplina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='utente',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='delegacao',
        ),
        migrations.AddField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
        migrations.DeleteModel(
            name='Delegacao',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
        migrations.DeleteModel(
            name='TipoOcorrencia',
        ),
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
