# Generated by Django 4.0.6 on 2023-11-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_documento_ocorrencia_remove_imagem_ocorrencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(default=1),
        ),
    ]
