# Generated by Django 4.0.6 on 2023-11-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_aluno_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
    ]
