# Generated by Django 4.0.6 on 2025-10-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_aluno_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(related_name='disciplinas', to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='turmas', to='app.aluno'),
        ),
    ]
