# Generated by Django 4.0.6 on 2023-09-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0014_remove_mentor_aluno_remove_mentor_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diades_mentor', to='app.aluno')),
                ('mentorando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diades_mentorando', to='app.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('sumario', models.CharField(max_length=100)),
                ('diade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='mentoria.diade')),
            ],
        ),
        migrations.CreateModel(
            name='Mentorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorandias', to='app.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorandias', to='app.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.CharField(max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to='app.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to='app.disciplina')),
            ],
        ),
    ]
