# Generated by Django 4.0.6 on 2023-09-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='ano_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to='mentoria.anolectivo'),
        ),
        migrations.AlterField(
            model_name='mentorando',
            name='ano_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorandias', to='mentoria.anolectivo'),
        ),
    ]
