# Generated by Django 4.0.6 on 2023-09-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0002_anolectivo_alter_mentor_ano_lectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diade',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diades_mentor', to='mentoria.mentor'),
        ),
        migrations.AlterField(
            model_name='diade',
            name='mentorando',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diades_mentorando', to='mentoria.mentorando'),
        ),
    ]
