# Generated by Django 4.0.6 on 2023-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0003_alter_diade_mentor_alter_diade_mentorando'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='nota',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mentorando',
            name='nota',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
