# Generated by Django 4.0.6 on 2023-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0004_mentor_nota_mentorando_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='diade',
            name='ano',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
