# Generated by Django 4.0.6 on 2023-09-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0005_diade_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diade',
            name='ano',
        ),
        migrations.AddField(
            model_name='diade',
            name='ano_lectivo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='diades', to='mentoria.anolectivo'),
        ),
    ]
