# Generated by Django 4.0.6 on 2023-09-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0009_remove_mentorando_nota_mentor_ativo_mentorando_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diade',
            name='ativo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
