# Generated by Django 4.2.1 on 2023-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0010_diade_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='data',
            field=models.DateTimeField(help_text='Informe a data da sessão no formato DD/MM/YYY HH:MM.'),
        ),
    ]
