# Generated by Django 4.0.6 on 2023-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0011_alter_sessao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='data',
            field=models.DateTimeField(help_text='Informe a data da sessão no formato DD/MM/YYYY HH:MM.'),
        ),
    ]
