# Generated by Django 4.2.1 on 2023-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0013_sessao_comfirmado_alter_sessao_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessao',
            old_name='comfirmado',
            new_name='confirmado',
        ),
    ]
