# Generated by Django 4.2.1 on 2023-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0015_sessao_avaliacao_mentor_sessao_avaliacao_mentorando_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='objetivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='observacoes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='planificacao_proxima_sessao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='recursos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='sumario',
            field=models.CharField(max_length=200),
        ),
    ]
