# Generated by Django 4.2.1 on 2024-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0016_alter_sessao_objetivo_alter_sessao_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='reportado',
            field=models.BooleanField(default=False),
        ),
    ]
