# Generated by Django 4.0.6 on 2025-10-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoria', '0017_sessao_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diade',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default='2025-10-01'),
            preserve_default=False,
        ),
    ]
