# Generated by Django 4.0.6 on 2024-11-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deisihub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='ordem',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
